### ISSUE TITLE
ChEMBL Parser missing information

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mychem.info#67]
Currently, we only fetch data through https://www.ebi.ac.uk/chembl/api/data/molecule?format=json, which is not comprehensive. Need to combine data from multiple ChEMBL API endpoints.

1.Mechanism of Action (https://www.ebi.ac.uk/chembl/api/data/mechanism?format=json)
2. Indication (https://www.ebi.ac.uk/chembl/api/data/drug_indication?format=json)
3. target prediction (https://www.ebi.ac.uk/chembl/api/data/target_prediction?format=json)

The final results should match the display on web interface (example): https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL744

**Comment by kevinxin90** [comment]
Other important properties to be added (if available in database):
1. Alternative forms

2. bioactivity (e.g. IC50)

3. similar compounds

**Comment by kevinxin90** [comment]
See current mychem representation of ChEMBL data here: http://mychem.info/v1/chem/CHEMBL744?fields=chembl

**Comment by kevinxin90** [comment]
@erikyao You might need to consider downloading the full ChEMBL database here: ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/

**Comment by erikyao** [comment]
No issues so far in the development for **Mechanism of Action** and **Drug Indication**

Issues on the **Target Prediction** data source:

- API [https://www.ebi.ac.uk/chembl/api/data/target_prediction](https://www.ebi.ac.uk/chembl/api/data/target_prediction) is deprecated since ChEMBL release 26 (currently we have ChEMBL 27)
  - See Release Log: [ChEMBL 26 Released](https://chembl.blogspot.com/2020/03/chembl-26-released.html) 

> We also plan to provide a new target prediction web service in the future. The current target prediction web service (https://www.ebi.ac.uk/chembl/api/data/target_prediction/) has now been deprecated.

- The target prediction information is not saved in ChEMBL database either
  - Check schemas here: ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/schema_documentation.html
- Seemingly there is an internal API queried by their own website: https://www.ebi.ac.uk/chembl/target-predictions, which takes one SMILES annotation and output the targets for the corresponding entity. 
  - E.g. Post data: `{"smiles":"Nc1nc2ccc(OC(F)(F)F)cc2s1"}` (SMILES of `CHEMBL744`) 
  - However we suspect its performance for our data dumping scenario. 

![image](https://user-images.githubusercontent.com/4813680/100140007-3151d600-2e45-11eb-8878-85fe12ecda2e.png)

![image](https://user-images.githubusercontent.com/4813680/100140225-842b8d80-2e45-11eb-8986-a0d063cd0f1d.png)

I'll ask the ChEMBL team when a new target prediction API will be released.

**Comment by erikyao** [comment]
To be fixed by [Pull Request#93](https://github.com/biothings/mychem.info/pull/93)

**Comment by erikyao** [comment]
TODO: Minor changes on drug-indication, drug-mechanism references

- Use shorter keys: `ref_id` => `id`, `ref_type` => `type`, `ref_url` => `url`
- Add a new entry for each reference object with its `ref_type` value as key, its`ref_id` value as value

E.g.

In the previous Pull Request, a drug-indication reference is like:

```yaml
"indication_refs": [
  {
    "ref_id": "NCT01910259",
    "ref_type": "ClinicalTrials",
    "ref_url": "https://clinicaltrials.gov/search?id=%22NCT01910259%22"
  }
]
```

The suggested format will be:

```yaml
"indication_refs": [
  {
    "ClinicalTrials": "NCT01910259",
    "id": "NCT01910259",
    "type": "ClinicalTrials",
    "url": "https://clinicaltrials.gov/search?id=%22NCT01910259%22"
  }
]
```
